export const TAXON_SERVICE_CLEAR_SEARCH = 'TAXON_SERVICE_CLEAR_SEARCH'
export const TAXON_SERVICE_CREATE_TAXON_FAIL = 'TAXON_SERVICE_CREATE_TAXON_FAIL'
export const TAXON_SERVICE_CREATE_TAXON_REQUEST =
  'TAXON_SERVICE_CREATE_TAXON_REQUEST'
export const TAXON_SERVICE_CREATE_TAXON_SUCCESS =
  'TAXON_SERVICE_CREATE_TAXON_SUCCESS'
export const TAXON_SERVICE_GET_TAXA_BY_NAME_FAIL =
  'TAXON_SERVICE_GET_TAXA_BY_NAME_FAIL'
export const TAXON_SERVICE_GET_TAXA_BY_NAME_REQUEST =
  'TAXON_SERVICE_GET_TAXA_BY_NAME_REQUEST'
export const TAXON_SERVICE_GET_TAXA_BY_NAME_SUCCESS =
  'TAXON_SERVICE_GET_TAXA_BY_NAME_SUCCESS'
export const TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_FAIL =
  'TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_FAIL'
export const TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_REQUEST =
  'TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_REQUEST'
export const TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_SUCCESS =
  'TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_SUCCESS'
export const TAXON_SERVICE_GET_TAXON_FAIL = 'TAXON_SERVICE_GET_TAXON_FAIL'
export const TAXON_SERVICE_GET_TAXON_REQUEST = 'TAXON_SERVICE_GET_TAXON_REQUEST'
export const TAXON_SERVICE_GET_TAXON_SUCCESS = 'TAXON_SERVICE_GET_TAXON_SUCCESS'
export const TAXON_SERVICE_UPDATE_SEARCH_FILTER_NAME =
  'TAXON_SERVICE_UPDATE_SEARCH_FILTER_NAME'
export const TAXON_SERVICE_UPDATE_TAXON_FAIL = 'TAXON_SERVICE_UPDATE_TAXON_FAIL'
export const TAXON_SERVICE_UPDATE_TAXON_REQUEST =
  'TAXON_SERVICE_UPDATE_TAXON_REQUEST'
export const TAXON_SERVICE_UPDATE_TAXON_SUCCESS =
  'TAXON_SERVICE_UPDATE_TAXON_SUCCESS'
