language: node_js

services:
  - docker

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

script:
  - yarn build:mock
  - yarn build:storybook
  - yarn test:coverage

after_success:
  - export PUSH_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo ""; fi)
  - echo "PUSH_BRANCH=$PUSH_BRANCH, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$PUSH_BRANCH" == "next" ]; then
    echo "Start mock docker build";
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dina-collections-ui-mock .;
    docker tag dina-collections-ui-mock dina/dina-collections-ui-mock;
    docker push dina/dina-collections-ui-mock;
    fi
  - if [ "$PUSH_BRANCH" == "master" ]; then
    echo "Start build";
    yarn build;
    echo "Start docker build";
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dina-collections-ui .;
    docker tag dina-collections-ui dina/dina-collections-ui;
    docker push dina/dina-collections-ui;
    fi
