export const USER_LOG_IN_REQUEST = 'USER_LOG_IN_REQUEST'
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOG_IN_FAIL = 'USER_LOG_IN_FAIL'
export const USER_LOG_OUT_REQUEST = 'USER_LOG_OUT_REQUEST'
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS'
export const USER_LOG_OUT_FAIL = 'USER_LOG_OUT_FAIL'
export const USER_GET_USER_REQUEST = 'USER_GET_USER_REQUEST'
export const USER_GET_USER_SUCCESS = 'USER_GET_USER_SUCCESS'
export const USER_GET_USER_FAIL = 'USER_GET_USER_FAIL'
export const USER_GET_USER_PREFERENCES_REQUEST =
  'USER_GET_USER_PREFERENCES_REQUEST'
export const USER_GET_USER_PREFERENCES_SUCCESS =
  'USER_GET_USER_PREFERENCES_SUCCESS'
export const USER_GET_USER_PREFERENCES_FAIL = 'USER_GET_USER_PREFERENCES_FAIL'

export const USER_UPDATE_USER_PREFERENCES_REQUEST =
  'USER_UPDATE_USER_PREFERENCES_REQUEST'
export const USER_UPDATE_USER_PREFERENCES_SUCCESS =
  'USER_UPDATE_USER_PREFERENCES_SUCCESS'
export const USER_UPDATE_USER_PREFERENCES_FAIL =
  'USER_UPDATE_USER_PREFERENCES_FAIL'
