export const TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_FAIL =
  'TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_FAIL'
export const TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_REQUEST =
  'TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_REQUEST'
export const TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_SUCCESS =
  'TAXON_SERVICE_GET_TAXA_FOR_LOOKUP_SUCCESS'
export const TAXON_SERVICE_UPDATE_SEARCH_QUERY =
  'TAXON_SERVICE_UPDATE_SEARCH_QUERY'
