import * as actionTypes from './actionTypes'

const expectedActionTypeValues = [
  'TAXON_SERVICE_CREATE_TAXON_FAIL',
  'TAXON_SERVICE_CREATE_TAXON_NAME_FAIL',
  'TAXON_SERVICE_CREATE_TAXON_NAME_REQUEST',
  'TAXON_SERVICE_CREATE_TAXON_NAME_SUCCESS',
  'TAXON_SERVICE_CREATE_TAXON_REQUEST',
  'TAXON_SERVICE_CREATE_TAXON_SUCCESS',
  'TAXON_SERVICE_GET_TAXA_FAIL',
  'TAXON_SERVICE_GET_TAXA_REQUEST',
  'TAXON_SERVICE_GET_TAXA_SUCCESS',
  'TAXON_SERVICE_GET_TAXON_FAIL',
  'TAXON_SERVICE_GET_TAXON_NAME_FAIL',
  'TAXON_SERVICE_GET_TAXON_NAME_REQUEST',
  'TAXON_SERVICE_GET_TAXON_NAME_SUCCESS',
  'TAXON_SERVICE_GET_TAXON_NAMES_FAIL',
  'TAXON_SERVICE_GET_TAXON_NAMES_REQUEST',
  'TAXON_SERVICE_GET_TAXON_NAMES_SUCCESS',
  'TAXON_SERVICE_GET_TAXON_REQUEST',
  'TAXON_SERVICE_GET_TAXON_SUCCESS',
  'TAXON_SERVICE_UPDATE_TAXON_FAIL',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_ACCEPTED_TO_TAXON_FAIL',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_ACCEPTED_TO_TAXON_REQUEST',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_ACCEPTED_TO_TAXON_SUCCESS',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_FAIL',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_REQUEST',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_SUCCESS',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_SYNONYM_TO_TAXON_FAIL',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_SYNONYM_TO_TAXON_REQUEST',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_SYNONYM_TO_TAXON_SUCCESS',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_VERNACULAR_TO_TAXON_FAIL',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_VERNACULAR_TO_TAXON_REQUEST',
  'TAXON_SERVICE_UPDATE_TAXON_NAME_VERNACULAR_TO_TAXON_SUCCESS',
  'TAXON_SERVICE_UPDATE_TAXON_PARENT_FAIL',
  'TAXON_SERVICE_UPDATE_TAXON_PARENT_REQUEST',
  'TAXON_SERVICE_UPDATE_TAXON_PARENT_SUCCESS',
  'TAXON_SERVICE_UPDATE_TAXON_REQUEST',
  'TAXON_SERVICE_UPDATE_TAXON_SUCCESS',
]

describe('dataModules/taxonService/actionTypes', () => {
  it('exports expected types', () => {
    expect(Object.values(actionTypes).sort()).toEqual(
      expectedActionTypeValues.sort()
    )
  })
})
