export const PLACE_SERVICE_CREATE_PLACE_FAIL = 'PLACE_SERVICE_CREATE_PLACE_FAIL'
export const PLACE_SERVICE_CREATE_PLACE_REQUEST =
  'PLACE_SERVICE_CREATE_PLACE_REQUEST'
export const PLACE_SERVICE_CREATE_PLACE_SUCCESS =
  'PLACE_SERVICE_CREATE_PLACE_SUCCESS'
export const PLACE_SERVICE_GET_PLACE_FAIL = 'PLACE_SERVICE_GET_PLACE_FAIL'
export const PLACE_SERVICE_GET_PLACE_REQUEST = 'PLACE_SERVICE_GET_PLACE_REQUEST'
export const PLACE_SERVICE_GET_PLACE_SUCCESS = 'PLACE_SERVICE_GET_PLACE_SUCCESS'
export const PLACE_SERVICE_GET_PLACES_FAIL = 'PLACE_SERVICE_GET_PLACES_FAIL'
export const PLACE_SERVICE_GET_PLACES_REQUEST =
  'PLACE_SERVICE_GET_PLACES_REQUEST'
export const PLACE_SERVICE_GET_PLACES_SUCCESS =
  'PLACE_SERVICE_GET_PLACES_SUCCESS'
export const PLACE_SERVICE_UPDATE_PLACE_FAIL = 'PLACE_SERVICE_UPDATE_PLACE_FAIL'
export const PLACE_SERVICE_UPDATE_PLACE_REQUEST =
  'PLACE_SERVICE_UPDATE_PLACE_REQUEST'
export const PLACE_SERVICE_UPDATE_PLACE_SUCCESS =
  'PLACE_SERVICE_UPDATE_PLACE_SUCCESS'
