exports.causeOfDeathType = require('./causeOfDeathType')
exports.establishmentMeansType = require('./establishmentMeansType')
exports.featureType = require('./featureType')
exports.identifierType = require('./identifierType')
exports.preparationType = require('./preparationType')
exports.typeSpecimenType = require('./typeSpecimenType')
