export const FEATURE_OBSERVATION_TYPE_NAMES = [
  'age',
  'ageStage',
  'conditionAtCollecting',
  'sex',
]

export const MAMMAL_FORM_NAME = 'mammalForm'

export const MODULE_NAME = 'collectionMammals'

const mapToDropDownOption = value => {
  return {
    key: value,
    textKey: value,
    value,
  }
}

export const CONTINENTS = [
  'Africa',
  'Antarctica',
  'Arctic Ocean',
  'Asia',
  'Atlantic Ocean',
  'Australia',
  'Europe',
  'North America',
  'Oceania',
  'Pacific Ocean',
  'South America',
].map(mapToDropDownOption)

export const COUNTRIES = [
  'Algeria',
  'Angola',
  'Antarctica',
  'Argentina',
  'ARGENTINA',
  'Australia',
  'Austria',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Belize',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'CAMBODIA',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Congo',
  'Congo, Democratic Republic of the',
  'Congo, The Democratic Republic of the',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Ecuador',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'France?',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'GIBRALTAR',
  'Greece',
  'Greenland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'GUINEA',
  'Guinea',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic of',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Kazakhstan',
  'Kenya',
  "Korea (the Democratic People's Republic of)",
  'Korea (the Republic of)',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Latvia/Estonia',
  'Lesotho',
  'Liberia',
  'Libya',
  'Lithuania',
  'Madagascar',
  'Malaysia',
  'Malta',
  'Mauritius',
  'Mexico',
  'Micronesia, Federated States of',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Nigeria',
  'Norfolk island',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestinian Territory, Occupied',
  'Panama',
  'Papua New Guinea',
  'Papua new guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Russian Federation',
  'Russian federation',
  'Russian Federation (Asian part)',
  'Russian Federation (European part)',
  'Rwanda',
  'RÃ©union',
  'Saint Helena',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Solomon islands',
  'Somalia',
  'South Africa',
  'South africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tanzania',
  'Tanzania, United Republic of',
  'Thailand',
  'THAILAND',
  'TOGO',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Kingdom',
  'United States',
  'United States of America',
  'Unknown',
  'unknown',
  'Uruguay',
  'USA',
  'Uzbekistan',
  'Venezuela',
  'Viet Nam',
  'Zambia',
  'ZIMBABWE',
  'Zimbabwe',
].map(mapToDropDownOption)

export const PROVINCES = [
  'Balearic Islands',
  'Adana',
  'Ahvenanmaa',
  'Akershus',
  'Alaska',
  'Alberta',
  'Alsace',
  'Altai',
  'Altaiskiy kray',
  'Altay',
  'Alto Paraguay',
  'Amazonas',
  'Amur',
  'An-Nil al-abyad',
  'Andalucia',
  'Anhui',
  'Annam',
  'Anseba',
  'Antioquia',
  'Apulia',
  'Arizona',
  'Arkhangelsk Oblast',
  'Arusha',
  'Assam',
  'Aust-Agder',
  'Azores',
  'Ba Shan Ho',
  'Baden-WÃ¼rttemberg',
  'Bahia',
  'Baleares',
  'Basso Giuba',
  'Bayern',
  'Begemdir and Simen',
  'Beijing',
  'Belize',
  'Beni',
  'BerIin',
  'Bihar',
  'Blekinge',
  'Blue Nile',
  'BohuslÃ¤n',
  'Bor County',
  'Brandenburg',
  'Brasilia',
  'British Columbia',
  'Budapest',
  'Buenos Aires',
  'Bundibugyo',
  'Busoga',
  'BÃ¶hmen',
  'Caffraria',
  'Cairo',
  'Calabria',
  'California',
  'Cape',
  'Cape Province',
  'Cape province',
  'Carchi',
  'Casablanca',
  'Castilla y Leon',
  'Cauca',
  'Central',
  'Central Annam',
  'Centre-Sud',
  'Chaco',
  'Chelyabinsk',
  'Chihli',
  'Chimbu',
  'Chita',
  'Chittatong Hill Tracts',
  'Chukotka',
  'Coast',
  'Cochabamba',
  'CoclÃ©',
  'Colorado',
  'Constanta',
  'Cunene',
  'Dalarna',
  'Dalsland',
  'Damaraland',
  'Demerara',
  'East',
  'East Kazakhstan',
  'Eastern',
  'Eastern Cape',
  'Erongo',
  'Espirito Santo',
  'Fianarantsoa',
  'Finnmark',
  'Florida',
  'Frederiksborg',
  'Fujian',
  'Fyn',
  'FÃ¤rÃ¶arna',
  'Gansu',
  'Gazankulu/Machangana',
  'Georgia',
  'Gobi desert',
  'Gotland',
  'Great Andaman',
  'Greenland',
  'Griqualand',
  'Guangdong',
  'Guayas',
  'Guera',
  'Guerrero',
  'GyÃ¶r-Sopron',
  'GÃ¤strikland',
  'Halland',
  'Hamburg',
  'Hardap',
  'Harer',
  'Hebei',
  'Hebei (Chihli)',
  'Hessen',
  'Highland',
  'Himachal Pradesh',
  'Hokkaido',
  'Holguin',
  'Hubei',
  'Hunan',
  'HÃ¤lsingland',
  'HÃ¤rjedalen',
  'Illinois',
  'Indre',
  'Irian Barat',
  'Irian Jaya',
  'Isola Ã¨ Elba',
  'Istanbul',
  'Ituri',
  'Jambi',
  'Jammu and Kashmir',
  'Java',
  'Jawa Barat',
  'Jiangsu',
  'Johor',
  'Jubbada Hoose',
  'JÃ¤mtland',
  'Kachin',
  'Kagera',
  'Kagoshima prefecture',
  'Kajiado',
  'Kalimantan',
  'Kamchatka',
  'Kamtschatka',
  'Kansu',
  'Kanyol',
  'Kao-hsiung Chuen-Shih',
  'Karaganda',
  'Karelia',
  'Karlovy Vary',
  'Kelantan',
  'Keski-Suomi',
  'Kevala',
  'Kigezi',
  'Kilimanjaro',
  'Kisoro',
  'Kivu',
  'Kizegi',
  'Kong Karls',
  'Kongo Central',
  'Kongo Central (Bas-Congo)',
  'Kordofan',
  'KrakÃ³w County',
  'Kunene',
  'Kuril Islands',
  'Kurilerna',
  'KwaZulu-Natal',
  'Kwazulu-Natal',
  'Kwazulu/Zulu',
  'Kymi',
  'KÃ¶benhavn',
  'La Paz',
  'Lam Dong',
  'Lappland',
  'Larecaja',
  'Liguria',
  'Limpopo',
  'LimÃ³n',
  'Loire-Atlantique',
  'Loiret',
  'London',
  'Loreto',
  'Los Rios',
  'Louisiana',
  'Lower Saxony',
  'Lule Lappmark',
  'Lule lappmark',
  'Lyantonde',
  'Lycksele Lappmark',
  'Lycksele lappmark',
  'Magadan',
  'Magadanskaia',
  'Magallanes',
  'Mahajanga',
  'Maharashtra',
  'Maine',
  'Majunga',
  'Maluku',
  'Maniema',
  'Mara',
  'Maranhao',
  'Marrakech-Tensift-Al Haouz',
  'Massachusetts',
  'Mato Grosso',
  'Mazandaran',
  'Medelpad',
  'Mendoza',
  'Merida',
  'Michigan',
  'Mikkeli',
  'Minnesota',
  'Missiones',
  'Mon State',
  'Montana',
  'Montevideo',
  'Moravia',
  'N. Tonkin',
  'Nairobi',
  'Napo',
  'Naryn',
  'Natal',
  'National Capital Region',
  'Nebraska',
  'Negeri Sembilan',
  'Nei Mongol (Inner Mongolia)',
  'Nei Mongol Zizhiqu',
  'Nenetsie',
  'New Jersey',
  'New South Wales',
  'New South wales',
  'New York',
  'Newton',
  'Nicobar Islands',
  'Niedersachsen',
  'Nord-Kivu',
  'Nordaustla',
  'Nordjylland',
  'Nordland',
  'Norra Kivu-provinsen',
  'Norrbotten',
  'North Carolina',
  'North Hamgyong',
  'North Kivu',
  'North Kivu Province',
  'North Pyongan',
  'North West Ngamiland',
  'North-Kivu',
  'North-Western',
  'Northern',
  'Novgorod',
  'Nueva Asuncion',
  'Nunavut',
  'Nyanza',
  'NÃ¤rke',
  'Oaxaca',
  'Ohio',
  'Okinawa',
  'Ombella-Mpoko',
  'Ontario',
  'Oppland',
  'Oregon',
  'Oriente',
  'Oulu',
  'Ovamboland',
  'Oxapampa',
  'Palawan',
  'Pando',
  'Papua',
  'Para',
  'ParaguarÃ­',
  'Parana',
  'ParÃ¡',
  'Pastaza',
  'Perak',
  'Pest',
  'Piaui',
  'Pichincha',
  'Piemonte',
  'Pite Lappmark',
  'Pite lappmark',
  'Presidente Hayes',
  'Qinghai',
  'Quang Tri',
  'Quebec',
  'Queensland',
  'Region Zealand',
  'Rift Valley',
  'RingkÃ¶bing',
  'Rio De Janeiro',
  'Rio Grande do Sul',
  'Rio Muni',
  'Rio San Juan',
  'Rio Tapajoz',
  'Rondonia',
  'Roraima',
  'Ruhengeri',
  'Rutshuru',
  'Sabah',
  'Sacha (Jakutien)',
  'Sachsen',
  'Sachsen-Anhalt',
  'Sakhalin',
  'Salamanca',
  'Salzburg',
  'Santa Catarina',
  'Santa Cruz',
  'Santiago del Estero',
  'Sao Paulo',
  'Sao TomÃ©',
  'Sarawak',
  'Sardegna',
  'Sardinia',
  'Sassari',
  'Schleswig-Holstein',
  'Scotland',
  'Selangor',
  'Sennar',
  'Sermersooq',
  'Shanxi',
  'Shewa',
  'Siberia',
  'Sibirskij',
  'Sichuan',
  'Sicilia',
  'Sikkim',
  'Sinai',
  'Sinaloa',
  'Sinnar',
  'SkÃ¥ne',
  'SmÃ¥land',
  'Somogy',
  'South',
  'South Annam',
  'South Carolina',
  'South Georgia',
  'South Matabeleland',
  'Southern',
  'Stirling',
  'Sud-Kivu',
  'Sud-Ouest',
  'Suhbaatar',
  'Sulawesi',
  'Sulawesi Utara',
  'Sumatra',
  'Suriname',
  'Sutherland',
  'Svalbard',
  'Sverdlovsk Oblast[',
  'SÃ¶dermanland',
  'SÃ¶r-TrÃ¶ndelag',
  'Tabora',
  'Tainan',
  'Talas',
  'Tamatave',
  'Tamil Nadu',
  'Tananarive',
  'Tanga',
  'Tarabulus',
  'Tasmania',
  'Taymyria',
  'Tehran',
  'Texas',
  'ThÃ¼ringen',
  'Tibet',
  'Tierra del Fuego',
  'Tokahi',
  'Toliara',
  'Tonkin',
  'Torne Lappmark',
  'Torne lappmark',
  'Toscana',
  'Transvaal',
  'Trincomalee',
  'Troms',
  'TromsÃ¶',
  'Tucuman',
  'Tulear',
  'Tunis Wa Al-Ahwaz',
  'Tuscany',
  'Ultima Esperanza',
  'Unknown',
  'Uppland',
  'Ural',
  'Uttar Pradesh',
  'Uusimaa',
  'Valais',
  'Vaud',
  'Vera Cruz',
  'Vestsjaellands',
  'Vestspitsbergen',
  'Victoria',
  'Vienna',
  'Vosges',
  'VÃ¤rmland',
  'VÃ¤sterbotten',
  'VÃ¤stergÃ¶tland',
  'VÃ¤stmanland',
  'Wales',
  'Walfis Bay',
  'West Bengal',
  'Western',
  'Western Australia',
  'Western Cape',
  'Windhoek',
  'Wisconsin',
  'Xinjiang',
  'Xinjiang Uygur',
  'XX',
  'Yakutia',
  'Yala',
  'Yamalia',
  'Zaire-Central/Bas-Zaire',
  'Ã–land',
  'Ã–stergÃ¶tland',
  'Ã–stfold',
  'Ã…land',
  'Ã…ngermanland',
  'Ã…sele Lappmark',
  'Ã…sele lappmark',
].map(mapToDropDownOption)

export const DISTRICTS = [
  'GaspÃ© Peninsula',
  'Algoma District',
  'AlnÃ¶',
  'archipelago',
  'Arjeplog',
  'Arjeplogs kommun',
  'Arvidsjaur kommun',
  'Bahia Negra',
  'Batouri',
  'Bergs kommun',
  'BingsjÃ¶',
  'BlidÃ¶',
  'Bodens kommun',
  'Bolaang Mongondow',
  'Bolaang-Mongodon',
  'BrÃ¤cke',
  'Caledon-distriktet',
  'Cape Colony',
  'Chaco',
  'Chapa',
  'Chukotka',
  'Cimalaka',
  'Djadjerad',
  'Dorotea',
  'Dufved',
  'Edsele',
  'EkerÃ¶ kommun',
  'Esperito Santo',
  'Essex Co',
  'Essex County',
  'FalkÃ¶ping',
  'FalkÃ¶ping, KÃ¤lvene',
  'Falu kommun',
  'FinnerÃ¶dja, Barrud',
  'FiskbÃ¤ckvÃ¥len',
  'Flen kommun',
  'Franklin Co',
  'Gagnef kommun',
  'Gmina Jerzmanowice-Przeginia',
  'GrÃ¤ngesberg',
  'GrÃ¤sÃ¶',
  'GÃ¤llivare',
  'GÃ¤vle kommun',
  'GÃ¤vleborgs lÃ¤n',
  'Hagfors',
  'Halle-Hunneberg',
  'Hennepin Co',
  'Hildesheim',
  'Hulu Langat',
  'Hyby kommun',
  'HÃ¤rjedalen',
  'Irocanga',
  'Jokkmokk',
  'Jokkmokks kommun',
  'Kalix',
  'Kamtschatka',
  'Kattergatt',
  'Kigezi',
  'Kiruna',
  'Kiruna kommun',
  'Kivu',
  'Kottayam area',
  'Krasnojarsk kraj',
  'Krokom',
  'Krokoms kommun',
  'Kronobergs lÃ¤n',
  'Lakhimpur assam',
  'LinkÃ¶pings kommun',
  'Ljusdal',
  'Ljusdals kommun',
  'Ludvika kommun',
  'Malung',
  'March Township',
  'Minshan',
  'Mora',
  'Nanshan',
  'Newtownmountkennedy',
  'Nisibetu, Bekkai',
  'Nordmark',
  'Oberfranken',
  'Ometepec',
  'Orange County',
  'Orsa',
  'Oshima',
  'Oskarshamns Kommun',
  'Pajala',
  'Pichinca',
  'Pichincha',
  'PiteÃ¥',
  'Pozuzo',
  'Preangar',
  'Quillacollo',
  'Ragunda',
  'Rio Amazonas',
  'Rio Madeira',
  'Rio Mbini',
  'Rio Tapajos',
  'RÃ¤ttvik',
  'RÃ¤ttviks kommun',
  'S. Iskarbo',
  'Santo',
  'Shimla',
  'SkedbrofjÃ¤llet',
  'SkÃ¶vde kommun',
  'Slite',
  'SollefteÃ¥',
  'SollefteÃ¥ kommun',
  'Sorata',
  'South Annam',
  'Staffanstorp',
  'Stockholm',
  'Storuman',
  'StrÃ¶msund',
  'StrÃ¶msunds kommun',
  'Sveg',
  'SÃ¤rna kronopark',
  'SÃ¤var',
  'TorsÃ¥s kommun',
  'Tving',
  'TÃ¤nnÃ¤s',
  'Uppsala',
  'Ust-Yansky',
  'Vaca DÃ­ez',
  'Vadsbo hÃ¤rad',
  'VagnhÃ¤rad, Karlberg gÃ¥rd',
  'Valdaysky',
  'Vallentuna',
  'Vendel',
  'Vetlanda, BrantÃ¥s',
  'Vittangi',
  'VÃ¤sterhaninge',
  'VÃ¤sternorrland',
  'VÃ¤stmanland',
  'Werchojansk',
  'Westchester County',
  'Yacuma',
  'Yakutskaya',
  'Ã–stersjÃ¶n',
  'Ã–verhogdal',
  'Ã–verkalix kommun',
  'Ã–vertorneÃ¥',
  'Ã–xabÃ¤ck',
  'Ã„lvdalen',
  'Ã„lvdalens kommun',
  'Ã„lvsdalen',
  'Ã…land',
  'Ã…nge',
  'Ã…nge kommun',
].map(mapToDropDownOption)
