import * as actionTypes from './actionTypes'

const expectedActionTypeValues = [
  'IDENTIFIER_SERVICE_CREATE_CATALOG_NUMBER_FAIL',
  'IDENTIFIER_SERVICE_CREATE_CATALOG_NUMBER_REQUEST',
  'IDENTIFIER_SERVICE_CREATE_CATALOG_NUMBER_SUCCESS',
  'IDENTIFIER_SERVICE_GET_CATALOG_NUMBER_FAIL',
  'IDENTIFIER_SERVICE_GET_CATALOG_NUMBER_REQUEST',
  'IDENTIFIER_SERVICE_GET_CATALOG_NUMBER_SUCCESS',
  'IDENTIFIER_SERVICE_GET_CATALOG_NUMBERS_FAIL',
  'IDENTIFIER_SERVICE_GET_CATALOG_NUMBERS_REQUEST',
  'IDENTIFIER_SERVICE_GET_CATALOG_NUMBERS_SUCCESS',
  'IDENTIFIER_SERVICE_UPDATE_CATALOG_NUMBER_FAIL',
  'IDENTIFIER_SERVICE_UPDATE_CATALOG_NUMBER_REQUEST',
  'IDENTIFIER_SERVICE_UPDATE_CATALOG_NUMBER_SUCCESS',
]

describe('dataModules/identifierService/actionTypes', () => {
  it('exports expected types', () => {
    expect(Object.values(actionTypes).sort()).toEqual(
      expectedActionTypeValues.sort()
    )
  })
})
