export const MODULE_NAME = 'storage'
export const ALL = 'all'
export const GROUP_1 = 'Level 1'
export const GROUP_2 = 'Level 2'
export const GROUP_3 = 'Level 3'
export const GROUP_4 = 'Level 4'
export const DISCONNECT_TAXON_NAME = 'DISCONNECT_TAXON_NAME'
export const ADD_NEW_TAXON_NAME = 'ADD_NEW_TAXON_NAME'
