export const TAXON_SERVICE_CREATE_TAXON_FAIL = 'TAXON_SERVICE_CREATE_TAXON_FAIL'
export const TAXON_SERVICE_CREATE_TAXON_REQUEST =
  'TAXON_SERVICE_CREATE_TAXON_REQUEST'
export const TAXON_SERVICE_CREATE_TAXON_SUCCESS =
  'TAXON_SERVICE_CREATE_TAXON_SUCCESS'
export const TAXON_SERVICE_GET_TAXA_BY_NAME_FAIL =
  'TAXON_SERVICE_GET_TAXA_BY_NAME_FAIL'
export const TAXON_SERVICE_GET_TAXA_BY_NAME_REQUEST =
  'TAXON_SERVICE_GET_TAXA_BY_NAME_REQUEST'
export const TAXON_SERVICE_GET_TAXA_BY_NAME_SUCCESS =
  'TAXON_SERVICE_GET_TAXA_BY_NAME_SUCCESS'
export const TAXON_SERVICE_GET_TAXON_FAIL = 'TAXON_SERVICE_GET_TAXON_FAIL'
export const TAXON_SERVICE_GET_TAXON_REQUEST = 'TAXON_SERVICE_GET_TAXON_REQUEST'
export const TAXON_SERVICE_GET_TAXON_SUCCESS = 'TAXON_SERVICE_GET_TAXON_SUCCESS'
export const TAXON_SERVICE_UPDATE_TAXON_FAIL = 'TAXON_SERVICE_UPDATE_TAXON_FAIL'
export const TAXON_SERVICE_UPDATE_TAXON_REQUEST =
  'TAXON_SERVICE_UPDATE_TAXON_REQUEST'
export const TAXON_SERVICE_UPDATE_TAXON_SUCCESS =
  'TAXON_SERVICE_UPDATE_TAXON_SUCCESS'
