exports.create = require('./create')
exports.getMany = require('./getMany')
exports.getOne = require('./getOne')
exports.getRelation = require('./getRelation')
exports.update = require('./update')
exports.updateRelation = require('./updateRelation')
exports.getVersion = require('./getVersion')
exports.getVersions = require('./getVersions')
