export const KEYBOARD_SHORTCUTS_SET_MODAL_HIDDEN =
  'KEYBOARD_SHORTCUTS_SET_MODAL_HIDDEN'
export const KEYBOARD_SHORTCUTS_SET_MODAL_VISIBLE =
  'KEYBOARD_SHORTCUTS_SET_MODAL_VISIBLE'
export const KEYBOARD_SHORTCUTS_TRIGGER = 'KEYBOARD_SHORTCUTS_TRIGGER'
