exports.agentApi = require('./agentApi')
exports.authApi = require('./authApi')
exports.specimenApi = require('./specimenApi')
exports.storageApi = require('./storageApi')
exports.localityApi = require('./localityApi')
exports.taxonApi = require('./taxonApi')
exports.statusApi = require('./statusApi')
