exports.WORD_DELIMITER = '( |\\.)'
exports.MATCH_ANY = '.*'
exports.STRING_START = '^'
exports.STRING_END = '$'
exports.NON_WHITESPACE = '(\\S)'
exports.WHITESPACE = '( )'
exports.NON_MATCHING = 'this-should-not-be-matching-anything'
