import * as actionTypes from './actionTypes'

const expectedActionTypeValues = [
  'LOCALITY_SERVICE_CREATE_CURATED_LOCALITY_FAIL',
  'LOCALITY_SERVICE_CREATE_CURATED_LOCALITY_REQUEST',
  'LOCALITY_SERVICE_CREATE_CURATED_LOCALITY_SUCCESS',
  'LOCALITY_SERVICE_GET_CURATED_LOCALITY_FAIL',
  'LOCALITY_SERVICE_GET_CURATED_LOCALITY_REQUEST',
  'LOCALITY_SERVICE_GET_CURATED_LOCALITY_SUCCESS',
  'LOCALITY_SERVICE_GET_CURATED_LOCALITIES_FAIL',
  'LOCALITY_SERVICE_GET_CURATED_LOCALITIES_REQUEST',
  'LOCALITY_SERVICE_GET_CURATED_LOCALITIES_SUCCESS',
  'LOCALITY_SERVICE_UPDATE_CURATED_LOCALITY_FAIL',
  'LOCALITY_SERVICE_UPDATE_CURATED_LOCALITY_REQUEST',
  'LOCALITY_SERVICE_UPDATE_CURATED_LOCALITY_SUCCESS',
]

describe('domainModules/localityService/actionTypes', () => {
  it('exports expected types', () => {
    expect(Object.values(actionTypes).sort()).toEqual(
      expectedActionTypeValues.sort()
    )
  })
})
