module.exports = [
  { group: 'bone-count', key: 'cranium' },
  { group: 'bone-count', key: 'mandibula' },
  { group: 'bone-count', key: 'vertebrae' },
  { group: 'bone-count', key: 'costae' },
  { group: 'bone-count', key: 'scapula' },
  { group: 'bone-count', key: 'humerus' },
  { group: 'bone-count', key: 'ulna' },
  { group: 'bone-count', key: 'radius' },
  { group: 'bone-count', key: 'manus' },
  { group: 'bone-count', key: 'pelvis' },
  { group: 'bone-count', key: 'femur' },
  { group: 'bone-count', key: 'tibia' },
  { group: 'bone-count', key: 'pedis' },
]
