const execute = require('./execute')

const {
  acquisitions,
  collectingInformation,
  collectionItems,
  deathInformation,
  determinations,
  featureObservations,
  identifiers,
  legacyData,
  nestToCore,
  originInformation,
  recordHistoryEvents,
  sourceData,
  specimen,
  taxonInformation,
} = require('./transformationFunctions')

const {
  decorateCauseOfDeathTypeKeyIdMap,
  decorateCustomTaxonNameTypeKeyIdMap,
  decorateEstablishmentMeansTypeKeyIdMap,
  decorateFeatureTypeKeyIdMap,
  decorateIdentifierTypeKeyIdMap,
  decoratePlaceKeyIdMap,
  decoratePreparationTypeKeyIdMap,
  decorateStorageLocationKeyIdMap,
  decorateTaxonKeyIdMap,
  decorateTypeSpecimenTypeKeyIdMap,
} = require('./globalDecorators')

exports.importDataFromFile = {
  description: 'Importing specimens from file',
  executeFunction: execute,
  globalDecorators: [
    decorateCauseOfDeathTypeKeyIdMap,
    decorateCustomTaxonNameTypeKeyIdMap,
    decorateEstablishmentMeansTypeKeyIdMap,
    decorateFeatureTypeKeyIdMap,
    decorateIdentifierTypeKeyIdMap,
    decoratePlaceKeyIdMap,
    decoratePreparationTypeKeyIdMap,
    decorateStorageLocationKeyIdMap,
    decorateTaxonKeyIdMap,
    decorateTypeSpecimenTypeKeyIdMap,
  ],
  srcFileName: 'specimens',
  transformationFunctions: [
    specimen,
    acquisitions,
    collectingInformation,
    collectionItems,
    deathInformation,
    determinations,
    featureObservations,
    identifiers,
    legacyData,
    originInformation,
    recordHistoryEvents,
    taxonInformation,
    nestToCore,
    sourceData,
  ],
}
