exports.authService = require('./authService')
exports.curatedListService = require('./curatedListService')
exports.placeService = require('./placeService')
// exports.organizationService = require('./organizationService')
exports.specimenService = require('./specimenService')
exports.statusService = require('./statusService')
exports.storageService = require('./storageService')
exports.taxonomyService = require('./taxonomyService')
