module.exports = [
  'agentService',
  'curatedListService',
  'placeService',
  'storageService',
  'taxonomyService',
  'authService',
  'curatedEventService',
  'externalEventService',
  'organizationService',
  'searchService',
  'specimenService',
  'statusService',
  'jobService',
  'historyService',
  'exportService',
  'identifierService',
]
