export const API_CALL_OPERATION_REQUEST = 'API_CALL_OPERATION_REQUEST'
export const API_CALL_OPERATION_SUCCESS = 'API_CALL_OPERATION_SUCCESS'
export const API_CALL_OPERATION_FAIL = 'API_CALL_OPERATION_FAIL'
