export const TAXONOMY_CLEAR_SEARCH = 'TAXONOMY_CLEAR_SEARCH'
export const TAXONOMY_FETCH_SEARCH_RESULTS_FAIL =
  'TAXONOMY_FETCH_SEARCH_RESULTS_FAIL'
export const TAXONOMY_FETCH_SEARCH_RESULTS_REQUEST =
  'TAXONOMY_FETCH_SEARCH_RESULTS_REQUEST'
export const TAXONOMY_FETCH_SEARCH_RESULTS_SUCCESS =
  'TAXONOMY_FETCH_SEARCH_RESULTS_SUCCESS'
export const TAXONOMY_UPDATE_SEARCH_FILTER_NAME =
  'TAXONOMY_UPDATE_SEARCH_FILTER_NAME'
