export const CATALOG_CARD = 'catalogCard'
export const CATALOG_CARD_DESCRIPTION = 'Creation of catalog card'
export const MAMMAL_FORM_NAME = 'mammalForm'
export const MODULE_NAME = 'collectionMammals'
export const SPECIMEN_FILTERS_FORM_NAME = 'specimenFilters'
