export const MODULE_NAME = 'curatedList'
export const OTHER_PREPARATION = 'other-preparation'
export const SKELETON = 'skeleton'
export const SKIN = 'skin'
export const WET_PREPARATION = 'wet-preparation'
